#include "openGL.h"


//context creation
PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB = NULL;
PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB = NULL;
PFNWGLSWAPINTERVALEXTPROC glSwapInterval = NULL;
//shaders & shader programs
PFNGLCREATESHADERPROC glCreateShader = NULL;
PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;
PFNGLUSEPROGRAMPROC glUseProgram = NULL;
PFNGLLINKPROGRAMPROC glLinkProgram = NULL;
PFNGLATTACHSHADERPROC glAttachShader = NULL;
PFNGLSHADERSOURCEPROC glShaderSource = NULL;
PFNGLCOMPILESHADERPROC glCompileShader = NULL;
PFNGLDELETESHADERPROC glDeleteShader = NULL;
PFNGLDELETEPROGRAMPROC glDeleteProgram = NULL;

void LoadOpenGLFunctions()
{
	//context creation
	LOAD_GL_FUNCTION(PFNWGLCREATECONTEXTATTRIBSARBPROC ,wglCreateContextAttribsARB);
	LOAD_GL_FUNCTION(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);
	LOAD_GL_FUNCTION_EXTENDED(PFNWGLSWAPINTERVALEXTPROC, glSwapInterval, wglSwapIntervalEXT);
	//shader programs
	LOAD_GL_FUNCTION(PFNGLCREATESHADERPROC, glCreateShader);
	LOAD_GL_FUNCTION(PFNGLCREATEPROGRAMPROC, glCreateProgram);
	LOAD_GL_FUNCTION(PFNGLUSEPROGRAMPROC, glUseProgram);
	LOAD_GL_FUNCTION(PFNGLLINKPROGRAMPROC, glLinkProgram);
	LOAD_GL_FUNCTION(PFNGLATTACHSHADERPROC, glAttachShader);
	LOAD_GL_FUNCTION(PFNGLSHADERSOURCEPROC, glShaderSource);
	LOAD_GL_FUNCTION(PFNGLCOMPILESHADERPROC, glCompileShader);
	LOAD_GL_FUNCTION(PFNGLDELETESHADERPROC, glDeleteShader);
	LOAD_GL_FUNCTION(PFNGLDELETEPROGRAMPROC, glDeleteProgram);
};